### ISSUE TITLE
为什么我在APP里打开那个链接总是提示“版本信息为空，请重新填写”

### ISSUE THREAD

**Issue by RAINighty** [KaguraMika/bili-suit-v3#4]
![DY ~9C7D8D X LOBUGN3`(4](https://user-images.githubusercontent.com/97167694/192143034-5ebd8147-64c3-4d5a-8e1a-1b1d3b7c0ef0.png)
缺少以上的东西

**Comment by KaguraMika** [comment]
运行后, 请将app中的响应复制并填写回此工具中

**Comment by RAINighty** [comment]
> 运行后, 请将app中的响应复制并填写回此工具中

这是填写后的，不清楚为什么会少东西

**Comment by KaguraMika** [comment]
> > 运行后, 请将app中的响应复制并填写回此工具中
> 
> 这是填写后的，不清楚为什么会少东西

请再往下翻翻, 此操作只是为了完善请求头
另外, 请勿删除或修改原有配置中除了 item_id 以外的参数

**Comment by RAINighty** [comment]
> > > 运行后, 请将app中的响应复制并填写回此工具中
> > 
> > 
> > 这是填写后的，不清楚为什么会少东西
> 
> 请再往下翻翻, 此操作只是为了完善请求头 另外, 请勿删除或修改原有配置中除了 item_id 以外的参数

感谢，已解决
