### ISSUE TITLE
2. 填写 `config.json` 中的 `item_id` （装扮ID），这里的装扮id是b站出装扮的名字吗

### ISSUE THREAD

**Issue by orrangee** [KaguraMika/bili-suit-v3#6]

**Comment by KaguraMika** [comment]
事装扮ID，不是装扮名称

**Comment by orrangee** [comment]
这个id是在哪里能看到的，我百度不到TAT

**Comment by KaguraMika** [comment]
https://api.bilibili.com/x/garb/v2/mall/partition/item/list?access_key=&appkey=1d8b6e7d45233436&csrf=&disable_rcmd=0&group_id=0&part_id=6&pn=1&ps=20&sort_type=2&statistics=%7B%22appId%22%3A1%2C%22platform%22%3A3%2C%22version%22%3A%226.84.0%22%2C%22abtest%22%3A%22%22%7D&ts=&user_info=&sign=

**Comment by orrangee** [comment]
谢谢你
