### ISSUE TITLE
大佬我想问一下多开本子能抢成功吗

### ISSUE THREAD

**Issue by daybreak321** [KaguraMika/bili-suit-v3#7]
比如我账号里b币很多，然后我用几台电脑同时开本子但都登这一个账号，每个本子只购买一个装扮，那最后的结果是多个装扮都能购买成功吗，还是会有风控被发现？

**Comment by KaguraMika** [comment]
1. 多开只需要开多几个终端就行
2. 之前有人测试，多开最好不要超过两个吧
3. 风控我也没摸清😥

**Comment by daybreak321** [comment]
明白了，谢谢大佬
